FROM mattiasegly/node-image:386 as builder

RUN apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	build-essential \
&& rm -rf /var/lib/apt/lists/* \
&& update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN npm install --global --only=production tileserver-gl-light

FROM mattiasegly/node-image:386

COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules/

RUN ln -s ../lib/node_modules/tileserver-gl-light/src/main.js /usr/local/bin/tileserver-gl-light

ENV CHOKIDAR_USEPOLLING=1
ENV CHOKIDAR_INTERVAL=500

VOLUME /data
WORKDIR /data
EXPOSE 8080

CMD ["tileserver-gl-light"]